blank_issues_enabled: false
contact_links:
    - name: ✨ Feature Request
      url: https://github.com/fulviusguelfi/nexusai/discussions/categories/feature-requests
      about: Share and vote on feature requests for NexusAI
    - name: 💬 NexusAI Discussions
      url: https://github.com/fulviusguelfi/nexusai/discussions
      about: Join our GitHub Discussions community for questions and support
